controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    carpool:
        path: /carpool
        controller: App\Controller\carpool::index
